#!/usr/bin/env python3
"""
codegen/gen_dict.py

Reads cl100k_base.tiktoken.gz and o200k_base.tiktoken.gz from --data-dir,
decompresses, parses the tiktoken base64 format, and emits C header files
(dict_cl100k.h, dict_o200k.h) into --out-dir.

Each header file contains:
  - static const uint8_t  XXX_ALL_TOKENS[]   — concatenated token bytes
  - static const uint32_t XXX_TOKEN_STARTS[] — offset array (num_tokens+1 entries)
  - #define XXX_NUM_TOKENS  <count>
  - #define XXX_HASH_FACTOR <17846336922010275747ULL>
"""
import argparse
import base64
import gzip
import sys
from pathlib import Path


HASH_FACTOR = 17846336922010275747  # same as Rust bpe-openai/build.rs


def read_tiktoken(data: str) -> list[bytes]:
    tokens = []
    for line in data.splitlines():
        line = line.strip()
        if not line:
            continue
        # format: "<base64>" <rank>
        encoded = line.split()[0]
        tokens.append(base64.b64decode(encoded))
    return tokens


def emit_header(name: str, tokens: list[bytes], out_path: Path) -> None:
    prefix = name.upper()

    all_bytes: list[int] = []
    starts: list[int] = [0]
    for tok in tokens:
        all_bytes.extend(tok)
        starts.append(len(all_bytes))

    num_tokens = len(tokens)

    lines = [
        f"/* Auto-generated by codegen/gen_dict.py -- do not edit */",
        f"#pragma once",
        f"#include <stdint.h>",
        f"",
        f"#define {prefix}_NUM_TOKENS   {num_tokens}U",
        f"#define {prefix}_HASH_FACTOR  {HASH_FACTOR}ULL",
        f"",
    ]

    # all_tokens byte array
    lines.append(f"static const uint8_t {prefix}_ALL_TOKENS[] = {{")
    chunk = 16
    for i in range(0, len(all_bytes), chunk):
        row = all_bytes[i : i + chunk]
        hex_row = ", ".join(f"0x{b:02x}" for b in row)
        lines.append(f"    {hex_row},")
    lines.append("};")
    lines.append("")

    # token_starts offset array
    lines.append(f"static const uint32_t {prefix}_TOKEN_STARTS[] = {{")
    chunk = 8
    for i in range(0, len(starts), chunk):
        row = starts[i : i + chunk]
        num_row = ", ".join(f"{s}U" for s in row)
        lines.append(f"    {num_row},")
    lines.append("};")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote {out_path}  ({num_tokens} tokens, {len(all_bytes)} bytes)")


def main():
    parser = argparse.ArgumentParser(description="Generate BPE dict C headers from tiktoken data")
    parser.add_argument("--data-dir", required=True, help="Directory containing *.tiktoken.gz files")
    parser.add_argument("--out-dir", required=True, help="Directory to write dict_*.h files into")
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    configs = [
        ("cl100k_base", "dict_cl100k.h"),
        ("o200k_base",  "dict_o200k.h"),
    ]

    for base_name, out_name in configs:
        gz_path = data_dir / f"{base_name}.tiktoken.gz"
        if not gz_path.exists():
            print(f"ERROR: {gz_path} not found", file=sys.stderr)
            sys.exit(1)

        print(f"Processing {gz_path.name} ...")
        with gzip.open(gz_path, "rt", encoding="utf-8") as f:
            data = f.read()

        tokens = read_tiktoken(data)
        out_path = out_dir / out_name
        emit_header(base_name.replace("_base", ""), tokens, out_path)

    print("codegen done.")


if __name__ == "__main__":
    main()
