#!/usr/bin/env python3
"""
codegen/fetch_pcre2.py

Downloads the PCRE2 source tarball and extracts the files needed for
static compilation into third_party/pcre2/.

Run once before building: python codegen/fetch_pcre2.py
"""
import argparse
import hashlib
import os
import shutil
import sys
import tarfile
import urllib.request
from pathlib import Path

HERE = Path(__file__).parent.parent.resolve()

# PCRE2 10.45 (latest stable as of 2026-03)
PCRE2_VERSION = "10.45"
PCRE2_URL = f"https://github.com/PCRE2Project/pcre2/releases/download/pcre2-{PCRE2_VERSION}/pcre2-{PCRE2_VERSION}.tar.gz"
PCRE2_SHA256 = "5b9b6a1b27f8a8dfcb52f5a7c027a5fd7444d0cc99bd7d8c6b7c29c48fdb6b73"  # placeholder

PCRE2_CONFIG_H = """\
/* pcre2_config.h: generated by fetch_pcre2.py for static embedding */
#define HAVE_INTTYPES_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_MEMMOVE 1
#define PCRE2_CODE_UNIT_WIDTH 8
#define SUPPORT_UNICODE 1
#define LINK_SIZE 2
#define PARENS_NEST_LIMIT 250
#define HEAP_LIMIT 20000000
#define MATCH_LIMIT 10000000
#define MATCH_LIMIT_DEPTH 10000000
#define MAX_NAME_COUNT 10000
#define MAX_NAME_SIZE 32
#define NEWLINE_DEFAULT 2
#define PCRE2_STATIC 1
"""


def fetch(dest: Path):
    dest.mkdir(parents=True, exist_ok=True)
    tarball = dest / f"pcre2-{PCRE2_VERSION}.tar.gz"

    if not tarball.exists():
        print(f"Downloading {PCRE2_URL} ...")
        urllib.request.urlretrieve(PCRE2_URL, tarball)
        print("Download complete.")

    print(f"Extracting to {dest} ...")
    with tarfile.open(tarball, "r:gz") as tf:
        tf.extractall(dest)

    extracted = dest / f"pcre2-{PCRE2_VERSION}"
    src_dest = dest / "src"
    if src_dest.exists():
        shutil.rmtree(src_dest)
    shutil.copytree(extracted / "src", src_dest)

    # Write our custom config.h into pcre2/ (one level up from src/)
    (dest / "config.h").write_text(PCRE2_CONFIG_H)

    # Copy pcre2.h if present
    pcre2_h = extracted / "src" / "pcre2.h"
    if not pcre2_h.exists():
        # Try .generic (fully-substituted version, usable directly as pcre2.h)
        pcre2_h_generic = extracted / "src" / "pcre2.h.generic"
        if pcre2_h_generic.exists():
            shutil.copy(pcre2_h_generic, dest / "pcre2.h")
            pcre2_h = dest / "pcre2.h"
        else:
            pcre2_h = extracted / "pcre2.h"
    if pcre2_h.exists() and pcre2_h != dest / "pcre2.h":
        shutil.copy(pcre2_h, dest / "pcre2.h")

    # chartables: generate from the bundled script or copy default
    chartables_tmpl = src_dest / "pcre2_chartables.c.dist"
    chartables_out = src_dest / "pcre2_chartables.c"
    if chartables_tmpl.exists() and not chartables_out.exists():
        shutil.copy(chartables_tmpl, chartables_out)

    print(f"PCRE2 {PCRE2_VERSION} ready at {dest}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dest", default=str(HERE / "third_party" / "pcre2"))
    args = parser.parse_args()
    fetch(Path(args.dest))


if __name__ == "__main__":
    main()
